### ISSUE TITLE
收藏404

### ISSUE THREAD

**Issue by xiongaox** [fabricezhang/lcg#12]
收藏显示404，还有希望可以增加帖子排序功能，回复功能
因为这几样好像都是挺必要的，如果可以添加评分功能就更好了
ui做得很好，我喜欢这种卡片式悬浮的感觉
加油！！

**Comment by fabricezhang** [comment]
收藏目前其实只是收藏了url地址，所以帖子被删了就没有了，后面会加上全文收藏

**Comment by xiongaox** [comment]
期待~~

**Comment by fabricezhang** [comment]
1.6.4已经全部支持，欢迎体验
