### ISSUE TITLE
建议仿QQ  将我的 放到左侧抽屉中

### ISSUE THREAD

**Issue by kangxiaohui** [fabricezhang/lcg#15]
建议仿QQ  将我的 放到左侧抽屉中

**Comment by fabricezhang** [comment]
> 建议仿QQ 将我的 放到左侧抽屉中

左侧抽屉有一个很大的问题就是会和系统的左滑动作有冲突，我现在用华为手机开了左滑返回以后，左抽屉打开很费劲
