### ISSUE TITLE
Readme 文档需要更新

### ISSUE THREAD

**Issue by pky2006** [fabricezhang/lcg#48]
Readme 文档显示的是 1.8.6，可论坛上给的链接是 1.8.7
![Readme 文档](https://user-images.githubusercontent.com/47812412/102310119-4b468a80-3fa5-11eb-83e9-7d131a5acb28.png "Readme 文档")
![论坛给的蓝奏云链接](https://user-images.githubusercontent.com/47812412/102310163-687b5900-3fa5-11eb-8f12-50dafc9b5f3d.png "论坛给的蓝奏云链接")

**Comment by fabricezhang** [comment]
已更新
